<a href="https://colab.research.google.com/github/ha713/hai/blob/main/CTAB_7_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.일한 시간과 시급을 계산하여 출력하는 코드
- 일한시간(hours_worked)
- 일한날(day_worked)
- 시급(pay_rate)
- 월급(monthly_pay)

In [ ]:
hours_worked = int(input("일한 시간을 입력하시오.: "))  # 사용자로부터 일한 시간을 입력받습니다.

day_worked = int(input("일한 날짜를 입력하시오.: "))# 사용자로부터 일한 날짜를 입력받습니다.

day_month = hours_worked * day_worked# 일한 시간과 일한 날짜를 곱하여 한 달 동안 총 근무 시간을 계산합니다.

pay_rate = int(input("시급을 입력하시오.(23년 시급 9620): "))# 사용자로부터 시급을 입력받습니다.

daily_pay = hours_worked * pay_rate # 일한 시간과 시급을 곱하여 일일 급여를 계산합니다.

monthly_pay = hours_worked * pay_rate * day_worked # 일한 시간, 시급, 일한 날짜를 곱하여 월급여를 계산합니다.

print(f'일한시간은 {hours_worked}이며, 시급은 {pay_rate}이고, 월급여는 {monthly_pay}입니다.') # 계산된 결과를 출력합니다.

일한 시간을 입력하시오.: 10
일한 날짜를 입력하시오.: 25
시급을 입력하시오.(23년 시급 9620): 9620
일한시간은 10이며, 시급은 9620이고, 월급여는 2405000입니다.


위 코드는 사용자로부터 일한 시간, 일한 날짜, 시급을 입력받아 월급여를 계산하고 출력하는 코드입니다.

hours_worked = int(input("일한 시간을 입력하시오.: ")): 사용자로부터 일한 시간을 정수형으로 입력받아 변수 hours_worked에 저장합니다.
day_worked = int(input("일한 날짜를 입력하시오.: ")): 사용자로부터 일한 날짜를 정수형으로 입력받아 변수 day_worked에 저장합니다.
day_month = hours_worked * day_worked: 일한 시간과 일한 날짜를 곱하여 한 달 동안 총 근무 시간을 계산하여 변수 day_month에 저장합니다.
pay_rate = int(input("시급을 입력하시오.(23년 시급 9620): ")): 사용자로부터 시급을 정수형으로 입력받아 변수 pay_rate에 저장합니다.
daily_pay = hours_worked * pay_rate: 일한 시간과 시급을 곱하여 일일 급여를 계산하여 변수 daily_pay에 저장합니다.
monthly_pay = hours_worked * pay_rate * day_worked: 일한 시간, 시급, 일한 날짜를 곱하여 월급여를 계산하여 변수 monthly_pay에 저장합니다.
print(f'일한시간은 {hours_worked}이며, 시급은 {pay_rate}이고, 월급여는 {monthly_pay}입니다.'): 계산된 결과를 출력합니다.
이렇게 코드는 사용자로부터 입력받은 정보를 바탕으로 월급여를 계산하고 출력하는 기능을 수행합니다.

2. 환전하는 코드를 작성
- 변수 won, usd, exchange
- 계산 won * usd


In [ ]:

usd = int(input("환전할 달러를 입력: ")) # 사용자로부터 환전할 달러를 입력받습니다.

won = int(input("달러의 환율금액을 입력하세요(231031: 1372원): "))# 사용자로부터 달러의 환율을 입력받습니다.

exchange = won * usd # 환전한 금액을 계산합니다.

print(f'환전하고 싶은 {usd}달러는 환율 {won}으로 계산하면, {exchange}원 입니다.') # 계산된 결과를 출력합니다.

환전할 달러를 입력: 500
달러의 환율금약 입력(231031: 1372원)1372
환전하고 싶은 500달러는 환율 1372으로 계산하면, 686000원 입니다. 


위 코드는 사용자로부터 환전할 달러와 달러의 환율을 입력받아 원화로 환전한 금액을 계산하고 출력하는 코드입니다.

usd = int(input("환전할 달러를 입력: ")): 사용자로부터 환전할 달러를 정수형으로 입력받아 변수 usd에 저장합니다.
won = int(input("달러의 환율금액을 입력하세요(231031: 1372원): ")): 사용자로부터 달러의 환율을 정수형으로 입력받아 변수 won에 저장합니다.
exchange = won * usd: 입력받은 달러와 환율을 곱하여 환전한 금액을 계산하여 변수 exchange에 저장합니다.
print(f'환전하고 싶은 {usd}달러는 환율 {won}으로 계산하면, {exchange}원 입니다.'): 계산된 결과를 출력합니다.
이 코드는 사용자로부터 입력받은 환전할 달러와 환율을 바탕으로 환전한 금액을 계산하여 출력하는 기능을 수행합니다.


3. 화씨를 섭씨로 섭씨를 화씨로 변경하는 코드
- 화씨를 섭씨로 ℉ = ℃ * 1.8 + 32
- 섭씨를 화씨로 ℃ = (℉ - 32)/1.8
- 변수 : 화씨 fahrenheit, 섭씨 celsius


In [ ]:

fahrenheit = int(input("화씨를 입력하시오.:"))# 사용자로부터 화씨 온도를 입력받습니다.


celsius = (fahrenheit - 32) / 1.8# 입력받은 화씨 온도를 섭씨 온도로 변환합니다.


print(celsius) # 변환된 섭씨 온도를 출력합니다.

화씨를 입력하시오.:100
37.77777777777778


위 코드는 사용자로부터 화씨 온도를 입력받아 이를 섭씨 온도로 변환하고 출력하는 코드입니다.

fahrenheit = int(input("화씨를 입력하시오.:")): 사용자로부터 화씨 온도를 정수형으로 입력받아 변수 fahrenheit에 저장합니다.
celsius = (fahrenheit - 32) / 1.8: 입력받은 화씨 온도를 섭씨 온도로 변환하기 위해 (화씨 - 32) / 1.8 연산을 수행하여 섭씨 온도를 계산하고 변수 celsius에 저장합니다.
print(celsius): 변환된 섭씨 온도를 출력합니다.
위 코드는 사용자로부터 입력받은 화씨 온도를 섭씨 온도로 변환하여 출력하는 기능을 수행합니다. 변환 공식인 (화씨 - 32) / 1.8을 활용하여 섭씨 온도를 계산하고 이를 출력합니다.

In [ ]:

celsius = float(input("섭씨를 입력하시오.:"))# 사용자로부터 섭씨 온도를 입력받습니다.


fahrenheit = celsius * 1.8 + 32# 입력받은 섭씨 온도를 화씨 온도로 변환합니다.


print(fahrenheit) # 변환된 화씨 온도를 출력합니다.
위 코드는 사용자로부터 섭씨

섭씨를 입력하시오.:37.77777777777778
100.0


위 코드는 사용자로부터 섭씨 온도를 입력받아 이를 화씨 온도로 변환하고 출력하는 코드입니다.

celsius = float(input("섭씨를 입력하시오.:")): 사용자로부터 섭씨 온도를 실수형으로 입력받아 변수 celsius에 저장합니다.
fahrenheit = celsius * 1.8 + 32: 입력받은 섭씨 온도를 화씨 온도로 변환하기 위해 섭씨 * 1.8 + 32 연산을 수행하여 화씨 온도를 계산하고 변수 fahrenheit에 저장합니다.
print(fahrenheit): 변환된 화씨 온도를 출력합니다.
위 코드는 사용자로부터 입력받은 섭씨 온도를 화씨 온도로 변환하여 출력하는 기능을 수행합니다. 변환 공식인 섭씨 * 1.8 + 32을 활용하여 화씨 온도를 계산하고 이를 출력합니다.